server.port=8080
spring.application.name=moniepoint-election-system
spring.data.mongodb.uri=mongodb://localhost:27017/moniepoint_election
spring.data.mongodb.database=moniepoint_election
spring.data.mongodb.auto-index-creation=true